### ISSUE TITLE
File caching doesn't seem to work

### ISSUE THREAD

**Issue by DanielVip3** [TryGhost/express-hbs#201]
I premise that I use express-hbs with production mode active (`NODE_ENV = "production"`, I also checked for Express' object and `cache: true`).
From what seems to happen from `blocked-at`:
```
2020-05-26T01:41:03: Blocked for 212.16068994140625ms, operation started here: [
'    at ReadFileContext.close (internal/fs/read_file_context.js:103:17)',
'    at FSReqCallback.readFileAfterRead [as oncomplete] (internal/fs/read_file_context.js:29:13)'
]
```
this operation blocks Node's event loop for 200ms and, when inspected well, looks called from `express-hbs` itself, in this function
```js
fs.readFile(filename, 'utf8', function(err, source) {
    if (err) return cb(err);

    var template = self.compile(source, filename);
    if (options.cache) {
            self.cache[filename] = {
                source: source,
                template: template
            };
    }
    return cb(null, source, template);
});
```
Now, the problem is that this operation happens everytime. On each request, on the same page, from the same user, rendering the same template with same data, for each user. It means this file is readed multiple times, and cache doesn't seem to be even used, even if, right before this function, the cache is checked.

What could be the cause? This is causing major performance issues in my application.
It'd be useful if anyone could reproduce the issue using `blocked-at` or directly editing `express-hbs`'s source code.
Sorry for bothering you if this happens to be an environment-specific problem, and thanks for any help.

**Comment by DanielVip3** [comment]
I'd like to add that, I tested hooking into `express-hbs`'s source - it doesn't look like this is the expected behaviour: cache gets setted, but also gets re-setted everytime.
The function which initializes it, express3, looks like it gets called lots of time, even if I have a single middleware.

```js
// Cache for templates, express 3.x doesn't do this for us
this.cache = {};
```

**Comment by DanielVip3** [comment]
No, okay, I'm sorry for opening this useless issue. It all was due to me using lots of `pm2` clusters.
It would be cool to have a single-process shared cache, tho, even if that would be impossible.
