### ISSUE TITLE
app.render throws Missing helper error

### ISSUE THREAD

**Issue by pavelvlasov** [TryGhost/express-hbs#53]
When I use res.render everything works fine, but app.render throws this error

```
Error: Missing helper: 'href:verify'
    at new Error (<anonymous>)
    at Error.Exception (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/exception.js:13:41)
    at Object.<anonymous> (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/base.js:57:13)
    at Object.eval (eval at <anonymous> (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:8:328)
    at /home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:86:31
    at /home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:465:21
    at renderTemplate (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/lib/hbs.js:358:13)
    at render (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/lib/hbs.js:405:5)
    at renderIt (/home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/lib/hbs.js:438:18)
    at /home/freakycue/projects/jobportal/jobportal/node_modules/express-hbs/lib/hbs.js:469:13
```

**Comment by nico1510** [comment]
@pavelvlasov I have the same problem. How did you solve it ?
